feat(fcsfile): add updateFcsFile
primitybio/cellengine-r-toolkit pull request #80
Opened 2022-04-10 20:59 UTC by gegnew

2022-04-12 16:28 UTC, zbjornson requested changes

2022-04-12 16:28 UTC, zbjornson commented on _pkgdown.yml
> +      - updateFcsFile
This file is alphabetical within sections. Can you swap these lines please?

2022-04-12 16:30 UTC, zbjornson requested changes

2022-04-14 15:02 UTC, gegnew commented on R/updateFcsFile.R
> +#' Accepted properties are:
It's weird, I'm definitely using Roxygen to render it, and it renders fine for me. I can't figure out what's going on, so :pushpin: pending

2022-04-14 15:52 UTC, zbjornson commented
Hm, did you forget to push? :)

2022-04-20 02:56 UTC, zbjornson approved these changes

2022-04-20 02:56 UTC, merged