src: Encouring use of `vertices` in createPolygonGate
primitybio/cellengine-r-toolkit pull request #87
Opened 2022-04-27 10:04 UTC by gegnew

Add a warning to `xVertices` and `yVertices`, and change the docs to
reflect this

2022-04-28 18:20 UTC, zbjornson requested changes

2022-04-28 18:20 UTC, zbjornson commented on CHANGELOG.md
> +- Deprecate `createRectangleGate` args `xVertices=c()` and
```suggestion
- Deprecate `createPolygonGate` args `xVertices=c()` and
```

2022-05-12 15:33 UTC, gegnew commented on CHANGELOG.md
> +- Deprecate `createRectangleGate` args `xVertices=c()` and
oops

2022-05-12 15:41 UTC, zbjornson approved these changes

2022-05-12 16:12 UTC, merged